spring:
  application:
    name: rest-service-6

  rabbitmq:
    host: rabbitmq


      
  cloud:
    stream:
      bindings:
        input:
          destination: my-rest-service-queue-1
          contentType: text/plain
          binder: rabbit

server:
  port: 16006