spring:
  application:
    name: ts-station-service
  redis:
    database: 0
    host: ts-station-redis
    port: 6379
    timeout: 8000 # ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://ts-user-mysql:3306/users?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://ts-station-mysql:3306/station?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
management:
  endpoints:
    web:
      exposure:
        include: prometheus
# HTTP Server
server:
  port: 12345  # HTTP (Tomcat) port

swagger:
  controllerPackage: fdse.microservice