spring:
  application:
    name: ts-consign-price-service
  data:
    mongodb:
      host: ts-consign-price-mongo
      database: ts
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: prometheus

# HTTP Server
server:
  port: 16110

swagger:
  controllerPackage: consignprice.controller