server:
  port: 12386

spring:
  application:
    name: ts-execute-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: execute.controller