version: '3'
services:

  ts-login-service:
    build: ts-login-service
    image: ts/ts-login-service
    restart: always
    ports:
      - 12342:12342
    networks:
      - my-network


  ts-sso-service:
    build: ts-sso-service
    image: ts/ts-sso-service
    restart: always
    ports:
      - 12349:12349
    networks:
      - my-network


networks:
    my-network:
      # driver: overlay
      driver: bridge





