apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-admin-order-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-admin-order-service
    spec:
      containers:
      - name: ts-admin-order-service
        image: 10.141.212.25:5555/f12/istio-zipkin-ts-admin-order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16112

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-admin-basic-info-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-admin-basic-info-service
    spec:
      containers:
      - name: ts-admin-basic-info-service
        image: 10.141.212.25:5555/f12/cluster-ts-food-map-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18767
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-admin-route-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-admin-route-service
    spec:
      containers:
      - name: ts-admin-route-service
        image: 10.141.212.25:5555/f12/cluster-ts-admin-route-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16113
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-admin-travel-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-admin-travel-service
    spec:
      containers:
      - name: ts-admin-travel-service
        image: 10.141.212.25:5555/f12/cluster-ts-admin-travel-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16114
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-admin-user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-admin-user-service
    spec:
      containers:
      - name: ts-admin-user-service
        image: 10.141.212.25:5555/f12/cluster-ts-admin-user-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16115
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-contacts-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-contacts-service
    spec:
      containers:
      - name: ts-contacts-service
        image: 10.141.212.25:5555/f12/cluster-ts-contacts-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12347
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-execute-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-execute-service
    spec:
      containers:
      - name: ts-execute-service
        image: 10.141.212.25:5555/f12/cluster-ts-execute-service
        imagePullPolicy: Always
        ports:
        ports:
        - containerPort: 12386
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-food-map-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-map-service
    spec:
      containers:
      - name: ts-food-map-service
        image: 10.141.212.25:5555/f12/cluster-ts-food-map-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18855
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-register-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-register-service
    spec:
      containers:
      - name: ts-register-service
        image: 10.141.212.25:5555/f12/cluster-ts-register-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12344
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-travel-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel-service
    spec:
      containers:
      - name: ts-travel-service
        image: 10.141.212.25:5555/f12/cluster-ts-travel-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12346
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-travel2-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel2-service
    spec:
      containers:
      - name: ts-travel2-service
        image: 10.141.212.25:5555/f12/cluster-ts-travel2-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16346
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-cancel-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-cancel-service
    spec:
      containers:
      - name: ts-cancel-service
        image: 10.141.212.25:5555/f12/cluster-ts-cancel-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18885
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-inside-payment-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-inside-payment-service
    spec:
      containers:
      - name: ts-inside-payment-service
        image: 10.141.212.25:5555/f12/cluster-ts-inside-payment-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18673
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-other-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-other-service
    spec:
      containers:
      - name: ts-order-other-service
        image: 10.141.212.25:5555/f12/cluster-ts-order-other-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12032
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-basic-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-basic-service
    spec:
      containers:
      - name: ts-basic-service
        image: 10.141.212.25:5555/f12/cluster-ts-basic-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15680
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-service
    spec:
      containers:
      - name: ts-order-service
        image: 10.141.212.25:5555/f12/cluster-ts-order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12031
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-sso-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-sso-service
    spec:
      containers:
      - name: ts-sso-service
        image: 10.141.212.25:5555/f12/cluster-ts-sso-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12349
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-assurance-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-assurance-service
    spec:
      containers:
      - name: ts-assurance-service
        image: 10.141.212.25:5555/f12/cluster-ts-assurance-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18888
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-food-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-service
    spec:
      containers:
      - name: ts-food-service
        image: 10.141.212.25:5555/f12/cluster-ts-food-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18856
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-consign-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-consign-service
    spec:
      containers:
      - name: ts-consign-service
        image: 10.141.212.25:5555/f12/cluster-ts-consign-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16111
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-consign-price-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-consign-price-service
    spec:
      containers:
      - name: ts-consign-price-service
        image: 10.141.212.25:5555/f12/cluster-ts-consign-price-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16110
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "350Mi"
            cpu: "300m"

---

apiVersion: v1
kind: Service
metadata:
  name: ts-cancel-service
spec:
  type: NodePort
  ports:
    - name: http-cancel
      port: 18885
      nodePort: 30085
  selector:
    app: ts-cancel-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-service
spec:
  ports:
    - name: http
      port: 12032
  selector:
   app: ts-order-other-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-service
spec:
  ports:
    - name: http
      port: 12031
  selector:
   app: ts-order-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-service
spec:
  ports:
    - name: http
      port: 18673
  selector:
   app: ts-inside-payment-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
spec:
  ports:
    - name: http
      port: 15680
  selector:
   app: ts-basic-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-sso-service
spec:
  ports:
    - name: http
      port: 12349
  selector:
   app: ts-sso-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-assurance-service
spec:
  ports:
    - name: http
      port: 18888
  selector:
   app: ts-assurance-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-food-service
spec:
  ports:
    - name: http
      port: 18856
  selector:
   app: ts-food-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-consign-service
spec:
  ports:
    - name: http
      port: 16111
  selector:
   app: ts-consign-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-service
spec:
  ports:
    - name: http
      port: 16110
  selector:
   app: ts-consign-price-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-basic-info-service
spec:
  ports:
    - name: http
      port: 18767
  selector:
   app: ts-admin-basic-info-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-route-service
spec:
  ports:
    - name: http
      port: 16113
  selector:
   app: ts-admin-route-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-travel-service
spec:
  ports:
    - name: http
      port: 16114
  selector:
   app: ts-admin-travel-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-user-service
spec:
  ports:
    - name: http
      port: 16115
  selector:
   app: ts-admin-user-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-contacts-service
spec:
  ports:
    - name: http
      port: 12347
  selector:
   app: ts-contacts-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-execute-service
spec:
  ports:
    - name: http
      port: 12386
  selector:
   app: ts-execute-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-food-map-service
spec:
  ports:
    - name: http
      port: 18855
  selector:
   app: ts-food-map-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-register-service
spec:
  ports:
    - name: http
      port: 12344
  selector:
   app: ts-register-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
spec:
  ports:
    - name: http
      port: 12346
  selector:
   app: ts-travel-service


---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel2-service
spec:
  ports:
    - name: http
      port: 16346
  selector:
   app: ts-travel2-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-admin-order-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 18885
      nodePort: 30112
  selector:
   app: ts-admin-order-service

---



