apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-basic-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-basic-service
    spec:
      containers:
      - name: ts-basic-service
        image: 10.141.212.25:5555/istio-error-instance-ts-basic-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15680

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-config-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-config-service
    spec:
      containers:
      - name: ts-config-service
        image: 10.141.212.25:5555/istio-error-instance-ts-config-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15679

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-other-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-other-service
    spec:
      containers:
      - name: ts-order-other-service
        image: 10.141.212.25:5555/istio-error-instance-ts-order-other-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12032

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-service
    spec:
      containers:
      - name: ts-order-service
        image: 10.141.212.25:5555/istio-error-instance-ts-order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12031

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-price-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-price-service
    spec:
      containers:
      - name: ts-price-service
        image: 10.141.212.25:5555/istio-error-instance-ts-price-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16579

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-route-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-route-service
    spec:
      containers:
      - name: ts-route-service
        image: 10.141.212.25:5555/istio-error-instance-ts-route-service
        imagePullPolicy: Always
        ports:
        - containerPort: 11178

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-seat-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-seat-service
    spec:
      containers:
      - name: ts-seat-service
        image: 10.141.212.25:5555/istio-error-instance-ts-seat-service
        imagePullPolicy: Always
        ports:
        - containerPort: 18898

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-station-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-station-service
    spec:
      containers:
      - name: ts-station-service
        image: 10.141.212.25:5555/istio-error-instance-ts-station-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12345

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-ticketinfo-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-ticketinfo-service
    spec:
      containers:
      - name: ts-ticketinfo-service
        image: 10.141.212.25:5555/istio-error-instance-ts-ticketinfo-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15681

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-train-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-train-service
    spec:
      containers:
      - name: ts-train-service
        image: 10.141.212.25:5555/istio-error-instance-ts-train-service
        imagePullPolicy: Always
        ports:
        - containerPort: 14567

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-travel2-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel2-service
    spec:
      containers:
      - name: ts-travel2-service
        image: 10.141.212.25:5555/istio-error-instance-ts-travel2-service
        imagePullPolicy: Always
        ports:
        - containerPort: 16346

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-travel-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel-service
    spec:
      containers:
      - name: ts-travel-service
        image: 10.141.212.25:5555/istio-error-instance-ts-travel-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12346

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-login-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-login-service
    spec:
      containers:
      - name: ts-login-service
        image: 10.141.212.25:5555/istio-error-instance-ts-login-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12342

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-verification-code-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-verification-code-service
    spec:
      containers:
      - name: ts-verification-code-service
        image: 10.141.212.25:5555/istio-error-instance-ts-verification-code-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15678

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-sso-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-sso-service
    spec:
      containers:
      - name: ts-sso-service
        image: 10.141.212.25:5555/istio-error-instance-ts-sso-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12349

---

apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
spec:
  ports:
    - name: http
      port: 15680
  selector:
   app: ts-basic-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
spec:
  ports:
    - name: http
      port: 15679
  selector:
   app: ts-config-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-service
spec:
  ports:
    - name: http
      port: 12032
  selector:
   app: ts-order-other-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-service
spec:
  ports:
    - name: http
      port: 12031
  selector:
   app: ts-order-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
spec:
  ports:
    - name: http
      port: 16579
  selector:
   app: ts-price-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-route-service
spec:
  ports:
    - name: http
      port: 11178
  selector:
   app: ts-route-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-seat-service
spec:
  ports:
    - name: http
      port: 18898
  selector:
   app: ts-seat-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
spec:
  ports:
    - name: http
      port: 12345
  selector:
   app: ts-station-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-ticketinfo-service
spec:
  ports:
    - name: http
      port: 15681
  selector:
   app: ts-ticketinfo-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-train-service
spec:
  ports:
    - name: http
      port: 14567
  selector:
   app: ts-train-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel2-service
spec:
  ports:
    - name: http
      port: 16346
  selector:
   app: ts-travel2-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
spec:
  ports:
    - name: http
      port: 12346
  selector:
   app: ts-travel-service


---

apiVersion: v1
kind: Service
metadata:
  name: ts-login-service
spec:
  ports:
    - name: http
      port: 12342
  selector:
   app: ts-login-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
spec:
  ports:
    - name: http
      port: 15678
  selector:
   app: ts-verification-code-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-sso-service
spec:
  ports:
    - name: http
      port: 12349
  selector:
   app: ts-sso-service

---