apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-mongo
    spec:
      containers:
      - name: ts-order-mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-other-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-other-mongo
    spec:
      containers:
      - name: ts-order-other-mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-inside-payment-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-inside-payment-mongo
    spec:
      containers:
      - name: ts-inside-payment-mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-account-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-account-mongo
    spec:
      containers:
      - name: ts-account-mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-login-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-login-service
    spec:
      containers:
      - name: ts-login-service
        image: 10.141.212.25:5555/f1/cluster-ts-login-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12342

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-verification-code-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-verification-code-service
    spec:
      containers:
      - name: ts-verification-code-service
        image: 10.141.212.25:5555/f1/cluster-ts-verification-code-service
        imagePullPolicy: Always
        ports:
        - containerPort: 15678

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-sso-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-sso-service
    spec:
      containers:
      - name: ts-sso-service
        image: 10.141.212.25:5555/f1/cluster-ts-sso-service
        imagePullPolicy: Always
        ports:
        - containerPort: 12349

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-mongo
spec:
  ports:
    - port: 27017
  selector:
   app: ts-order-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-mongo
spec:
  ports:
    - port: 27017
  selector:
   app: ts-order-other-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-mongo
spec:
  ports:
    - port: 27017
  selector:
   app: ts-inside-payment-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-account-mongo
spec:
  ports:
    - port: 27017
  selector:
   app: ts-account-mongo

---

apiVersion: v1
kind: Service
metadata:
  name: ts-login-service
spec:
  ports:
    - name: http
      port: 12342
  selector:
   app: ts-login-service

---

apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
spec:
  ports:
    - name: http
      port: 15678
  selector:
   app: ts-verification-code-service

---


