server:
  port: 16114

spring:
  application:
    name: ts-admin-travel-service
management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: admintravel.controller