server:
  port: 16115

spring:
  application:
    name: ts-admin-user-service
management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: adminuser.controller
