server:
  port: 18767

spring:
  application:
    name: ts-admin-basic-info-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: adminbasic.microservice