server:
  port: 18885  # HTTP (Tomcat) port

spring:
  application:
    name: ts-cancel-service
management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: cancel.controller