server:
  port: 15680

spring:
  application:
    name: ts-basic-service
management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: fdse.microservice.controller