server:
  port: 16113

spring:
  application:
    name: ts-admin-route-service
management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: adminroute.controller

