server:
  port: 18856

spring:
  application:
    name: ts-food-service
  datasource:
    url: jdbc:mysql://ts-food-mysql:3306/food?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
#        use_sql_comments: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: foodsearch.controller