# HTTP Server
server:
  port: 14322  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-plan-service
management:
  endpoints:
    web:
      exposure:
        include: prometheus

swagger:
  controllerPackage: travelplan.controller