server:
  port: 12340
spring:
  application:
    name: ts-auth-service
  data:
    mongodb:
      host: ts-auth-mongo
      database: ts-auth-mongo
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: auth.controller