server:
  port: 16112

spring:
  application:
    name: ts-admin-order-service
management:
  endpoints:
    web:
      exposure:
        include: prometheus

swagger:
  controllerPackage: adminorder.controller
