# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port

spring:
  application:
    name: ts-ticketinfo-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus
swagger:
  controllerPackage: ticketinfo.controller